const ExpressError = require('./ExpressError')


module.exports  = fn => {
    return async (req, res, next) => {
      try {
        await fn(req, res, next)
      } catch (e) {
        next(e)
      }
    }
  }
  